
GET http://localhost:8080/playlists HTTP/1.1

###

GET http://localhost:8080/playlists/4 HTTP/1.1

###

GET http://localhost:8080/playlists/4/tracks HTTP/1.1

###

GET http://localhost:8080/tracks HTTP/1.1

###

POST http://localhost:8080/playlists HTTP/1.1
content-type: application/json

{ "title": "bateau"}

###

POST http://localhost:8080/playlists/3/tracks HTTP/1.1
content-type: application/json

{ "title": "Plamondon", "uri": "https://youtu.be/uWPnd2p-WhY", "master_id":4}

###

DELETE http://localhost:8080/playlists/4 HTTP/1.1